# -*- coding: utf-8 -*-
"""LogReg_Earthquake.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HL7ov8cf5koT0kxXCDL0daX2ZAvfkrZL
"""

# IMPORT LIBRARIES

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from imblearn.over_sampling import SMOTE #for balancing
from imblearn.under_sampling import RandomUnderSampler #for balancing
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report

# READ THE FILE

from google.colab import drive
drive.mount("/content/drive", force_remount=True)

Equake = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Earthquake_data.csv")

# Drop unnecessary column plus its a string (ID_code)
Equake = Equake.drop("building_id",  axis=1)

Equake.head()

# SPLITTING THE DATA

Feature_matrix = Equake.drop("damage_grade", axis=1)

Target_vector = Equake["damage_grade"]

Feature_matrix_train, Feature_matrix_test, Target_vector_train, Target_vector_test = train_test_split (Feature_matrix,Target_vector, test_size=0.2, random_state=42)

"""# SMOTE oversampling

smote = SMOTE(random_state=42)

Feature_matrix_train_res, Target_vector_train_res = smote.fit_resample(Feature_matrix_train, Target_vector_train)""" #didnt fix the imbalancing so used Undersampling with RUS

# RUS undersampling

rus = RandomUnderSampler(random_state=42)
X_resampled, y_resampled = rus.fit_resample(Feature_matrix_train, Target_vector_train)

# BASELINE MODEL (Check the baseline in which to compare model accuracy. This will give accuracy to beat )

Dummy_clf = DummyClassifier(strategy='most_frequent')

Dummy_clf.fit(Feature_matrix_train,Target_vector_train)

Target_vector_pred_dummy = Dummy_clf.predict(Feature_matrix_test)

print(f"Baseline Accuracy or Score to beat: {accuracy_score(Target_vector_test, Target_vector_pred_dummy)}")

# # FIT AND TRAIN

# Logistic_model = LogisticRegression(max_iter=3000)

# Logistic_model.fit (Feature_matrix_train,Target_vector_train)

# Identify non-numeric columns in the training data
non_numeric_cols = Feature_matrix_train.select_dtypes(exclude=np.number).columns
print("Non-numeric columns:", non_numeric_cols)

# Apply one-hot encoding to the training and testing data
Feature_matrix_train_encoded = pd.get_dummies(Feature_matrix_train, columns=non_numeric_cols, drop_first=True)
Feature_matrix_test_encoded = pd.get_dummies(Feature_matrix_test, columns=non_numeric_cols, drop_first=True)

# Ensure that both training and testing sets have the same columns after one-hot encoding
# This is important if some categories are present in one set but not the other
train_cols = Feature_matrix_train_encoded.columns
test_cols = Feature_matrix_test_encoded.columns

missing_in_test = set(train_cols) - set(test_cols)
for c in missing_in_test:
    Feature_matrix_test_encoded[c] = 0
# Ensure the order of columns is the same
Feature_matrix_test_encoded = Feature_matrix_test_encoded[train_cols]

# Now fit the Logistic Regression model with the encoded data
Logistic_model = LogisticRegression(max_iter=3000)

# Use the resampled data (X_resampled, y_resampled) for training the model
# Make sure to encode X_resampled as well
X_resampled_encoded = pd.get_dummies(X_resampled, columns=non_numeric_cols, drop_first=True)

# Ensure X_resampled_encoded has the same columns as Feature_matrix_train_encoded
missing_in_resampled = set(train_cols) - set(X_resampled_encoded.columns)
for c in missing_in_resampled:
    X_resampled_encoded[c] = 0
X_resampled_encoded = X_resampled_encoded[train_cols]


Logistic_model.fit(X_resampled_encoded, y_resampled)

print("Logistic Regression model fitted successfully.")

# MODEL SCORE CHECK

Model_accuracy = Rf_clf.score(Feature_matrix_test,Target_vector_test)

print(f"Rf_accuracy: {Model_accuracy}")

# PREDICTION

Prediction = Rf_clf.predict(Feature_matrix_test)

Prediction

# CONFUSION MATRIX TEST

cf_matrix = confusion_matrix(Target_vector_test, Prediction)
cf_matrix

# CONFUSION MATRIX TEST VIZ

group_names = ['True+','False+','False-','True-']
group_counts = ['{0:0.0f}'.format(value) for value in
                cf_matrix.flatten()]
group_percentages = ['{0:.2%}'.format(value) for value in
                     cf_matrix.flatten()/np.sum(cf_matrix)]
labels = [f"{v1}\n{v2}\n{v3}"
          for v1, v2, v3 in
          zip(group_names,group_counts,group_percentages)]
labels = np.asarray(labels).reshape(2,2)
sns.heatmap(cf_matrix, annot=labels, fmt='', cmap='Blues')

# BROAD REPORT

Matrix = classification_report(Target_vector_test, Prediction)

print('classification report : \n',Matrix)